[package]
name = "tquic_py"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }
tquic = { path = "..", version = "1.5.0"}
env_logger = "0.9"
log = "0.4"
bytes = "1"

[lib]
crate-type = ["lib", "cdylib"]